config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  
  resources :roots#, only: :index
  resources :admins#, only: :index
  resources :customers#, only: :index
end

app/models/root.rb
class Root < ApplicationRecord
  has_one :user, as: :userable, dependent: :destroy

  validates :name, presence: true

  accepts_nested_attributes_for :user
end

app/controllers/roots_controller.rb
class RootsController < ApplicationController
  before_action :authenticate_and_authorize!
  before_action :set_root, only: %i[ show edit update destroy ]

  # GET /roots or /roots.json
  def index
    @roots = Root.all
  end

  # GET /roots/1 or /roots/1.json
  def show
  end

  # GET /roots/new
  def new
    @root = Root.new
  end

  # GET /roots/1/edit
  def edit
  end

  # POST /roots or /roots.json
  def create
    @root = Root.new(root_params)

    respond_to do |format|
      if @root.save
        format.html { redirect_to root_url(@root), notice: "Root was successfully created." }
        format.json { render :show, status: :created, location: @root }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @root.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roots/1 or /roots/1.json
  def update
    respond_to do |format|
      if @root.update(root_params)
        format.html { redirect_to root_url(@root), notice: "Root was successfully updated." }
        format.json { render :show, status: :ok, location: @root }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @root.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roots/1 or /roots/1.json
  def destroy
    @root.destroy

    respond_to do |format|
      format.html { redirect_to roots_url, notice: "Root was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_root
      @root = Root.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def root_params
      params.require(:root).permit(:name)
    end
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/views/roots/_form.html.erb
<%= form_with(model: root) do |form| %>
  <% if root.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(root.errors.count, "error") %> prohibited this root from being saved:</h2>

      <ul>
        <% root.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/roots/_root.html.erb
<div id="<%= dom_id root %>">
  <p>
    <strong>Name:</strong>
    <%= root.name %>
  </p>

</div>

app/views/roots/edit.html.erb
<h1>Editing root</h1>

<%= render "form", root: @root %>

<br>

<div>
  <%= link_to "Show this root", @root %> |
  <%= link_to "Back to roots", roots_path %>
</div>

app/views/roots/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Roots</h1>

<div id="roots">
  <% @roots.each do |root| %>
    <%= render root %>
    <p>
      <%= link_to "Show this root", root %>
    </p>
  <% end %>
</div>

<%= link_to "New root", new_root_path %>

app/views/roots/new.html.erb
<h1>New root</h1>

<%= render "form", root: @root %>

<br>

<div>
  <%= link_to "Back to roots", roots_path %>
</div>

app/views/roots/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @root %>

<div>
  <%= link_to "Edit this root", edit_root_path(@root) %> |
  <%= link_to "Back to roots", roots_path %>

  <%= button_to "Destroy this root", @root, method: :delete %>
</div>